- hosts: all
  gather_facts: True
  vars:
    group_name: galaxy
    ftp_root_dir: /ftp_data
    random_user: '{{ r_user }}'
    random_clear_text_password: '{{ r_password }}'
  tasks:
    - name: set home directory
      set_fact: home_dir="{{ftp_root_dir}}/{{random_user}}"

    - name: create random SALT to crypt password
      shell: cat /dev/urandom | tr -dc 'qwertQWERTasdfgASDFGzxcvbZXCVB' | head -c12
      register: random_salt_json

    - name: set random_salt var
      set_fact: random_salt="{{random_salt_json.stdout}}"

    - name: encrypt password
      shell: mkpasswd -m sha-512 {{ random_clear_text_password }} {{ random_salt }}
      register: encrypted_password_json

    - name: set encrypted_password var
      set_fact: encrypted_password="{{encrypted_password_json.stdout}}"

    - name: create new users
      become: yes
      become_method: sudo
      user: name={{ random_user }} shell=/usr/sbin/nologin comment="random user"  group={{ group_name }} home={{ home_dir }} password={{ encrypted_password }} state=present force=yes remove=yes

    - name: change permission home directory
      become: yes
      become_method: sudo
      shell: chmod -R 0776 {{ home_dir }}/ && chown {{ random_user }}:{{ group_name}} {{ home_dir }}
